"""ML Knowledge Graph data — nodes and edges."""

NODES = {
    # label: (level, category)

    # ── Foundations ──────────────────────────────────────────────────────────
    "Linear Algebra":           (0, "foundation"),
    "Calculus":                 (0, "foundation"),
    "Probability & Stats":      (0, "foundation"),
    "Python":                   (0, "foundation"),
    "Information Theory":       (0, "foundation"),
    "Optimization Theory":      (0, "foundation"),
    "Numerical Methods":        (0, "foundation"),

    # ── Core ML Concepts ─────────────────────────────────────────────────────
    "Loss Functions":           (1, "core"),
    "Gradient Descent":         (1, "core"),
    "Backpropagation":          (1, "core"),
    "Regularization":           (1, "core"),
    "Feature Engineering":      (1, "core"),
    "Cross-Validation":         (1, "core"),
    "Bias-Variance Tradeoff":   (1, "core"),
    "Hyperparameter Tuning":    (1, "core"),
    "Data Preprocessing":       (1, "core"),
    "Evaluation Metrics":       (1, "core"),

    # ── Classical / Supervised ───────────────────────────────────────────────
    "Linear Regression":        (2, "supervised"),
    "Logistic Regression":      (2, "supervised"),
    "Decision Trees":           (2, "supervised"),
    "SVM":                      (2, "supervised"),
    "k-NN":                     (2, "supervised"),
    "Naive Bayes":              (2, "supervised"),
    "Ridge & Lasso":            (2, "supervised"),

    # ── Unsupervised ─────────────────────────────────────────────────────────
    "k-Means":                  (2, "unsupervised"),
    "PCA":                      (2, "unsupervised"),
    "DBSCAN":                   (2, "unsupervised"),
    "Gaussian Mixture Models":  (2, "unsupervised"),
    "Anomaly Detection":        (3, "unsupervised"),
    "Autoencoders":             (3, "unsupervised"),
    "Variational Autoencoders": (4, "unsupervised"),

    # ── Ensemble ─────────────────────────────────────────────────────────────
    "Bagging":                  (3, "ensemble"),
    "Boosting":                 (3, "ensemble"),
    "Random Forest":            (3, "ensemble"),
    "Gradient Boosting":        (3, "ensemble"),
    "XGBoost":                  (3, "ensemble"),
    "LightGBM":                 (3, "ensemble"),
    "Stacking":                 (3, "ensemble"),

    # ── Neural Networks ──────────────────────────────────────────────────────
    "Activation Functions":     (2, "neural"),
    "Neural Networks":          (3, "neural"),
    "Batch Normalization":      (3, "neural"),
    "Dropout":                  (3, "neural"),
    "Optimizers (Adam/SGD)":    (3, "neural"),
    "CNNs":                     (4, "neural"),
    "RNNs":                     (4, "neural"),
    "LSTMs":                    (4, "neural"),
    "GRUs":                     (4, "neural"),
    "Attention Mechanism":      (4, "neural"),
    "Residual Networks":        (4, "neural"),
    "Graph Neural Networks":    (4, "neural"),

    # ── Advanced ─────────────────────────────────────────────────────────────
    "Transformers":             (5, "advanced"),
    "BERT / GPT":               (5, "advanced"),
    "Diffusion Models":         (5, "advanced"),
    "GANs":                     (5, "advanced"),
    "Reinforcement Learning":   (5, "advanced"),
    "Policy Gradient":          (5, "advanced"),
    "Self-Supervised Learning": (5, "advanced"),
    "Contrastive Learning":     (5, "advanced"),
    "Vision Transformers":      (5, "advanced"),
    "Multimodal Models":        (5, "advanced"),

    # ── Expert ───────────────────────────────────────────────────────────────
    "LLM Fine-tuning":          (6, "advanced"),
    "RLHF":                     (6, "advanced"),
    "Meta-Learning":            (6, "advanced"),
    "Neural Architecture Search": (6, "advanced"),
    "Federated Learning":       (6, "advanced"),
    "Quantization & Pruning":   (6, "advanced"),
    "AI Agents":                (6, "advanced"),
    "RAG":                      (6, "advanced"),
}

EDGES = [
    # Foundations → Core
    ("Linear Algebra", "Gradient Descent"),
    ("Linear Algebra", "PCA"),
    ("Linear Algebra", "SVM"),
    ("Linear Algebra", "Neural Networks"),
    ("Calculus", "Gradient Descent"),
    ("Calculus", "Backpropagation"),
    ("Calculus", "Optimization Theory"),
    ("Probability & Stats", "Loss Functions"),
    ("Probability & Stats", "Logistic Regression"),
    ("Probability & Stats", "Naive Bayes"),
    ("Probability & Stats", "Gaussian Mixture Models"),
    ("Information Theory", "Loss Functions"),
    ("Information Theory", "Evaluation Metrics"),
    ("Optimization Theory", "Gradient Descent"),
    ("Optimization Theory", "Optimizers (Adam/SGD)"),
    ("Numerical Methods", "Gradient Descent"),
    ("Python", "Feature Engineering"),
    ("Python", "Data Preprocessing"),

    # Core → Supervised
    ("Loss Functions", "Linear Regression"),
    ("Loss Functions", "Logistic Regression"),
    ("Loss Functions", "Neural Networks"),
    ("Gradient Descent", "Linear Regression"),
    ("Gradient Descent", "Neural Networks"),
    ("Gradient Descent", "Gradient Boosting"),
    ("Backpropagation", "Neural Networks"),
    ("Regularization", "Linear Regression"),
    ("Regularization", "Ridge & Lasso"),
    ("Regularization", "Dropout"),
    ("Regularization", "Batch Normalization"),
    ("Bias-Variance Tradeoff", "Regularization"),
    ("Bias-Variance Tradeoff", "Cross-Validation"),
    ("Cross-Validation", "Hyperparameter Tuning"),
    ("Feature Engineering", "Linear Regression"),
    ("Data Preprocessing", "Feature Engineering"),
    ("Evaluation Metrics", "Cross-Validation"),
    ("Activation Functions", "Neural Networks"),

    # Supervised
    ("Linear Regression", "Ridge & Lasso"),
    ("Decision Trees", "Random Forest"),
    ("Decision Trees", "Gradient Boosting"),
    ("Decision Trees", "Bagging"),
    ("Decision Trees", "Boosting"),
    ("Bagging", "Random Forest"),
    ("Boosting", "Gradient Boosting"),
    ("Gradient Boosting", "XGBoost"),
    ("Gradient Boosting", "LightGBM"),
    ("Random Forest", "Stacking"),
    ("XGBoost", "Stacking"),

    # Unsupervised
    ("k-Means", "DBSCAN"),
    ("PCA", "Anomaly Detection"),
    ("Gaussian Mixture Models", "Anomaly Detection"),
    ("Autoencoders", "Variational Autoencoders"),
    ("Neural Networks", "Autoencoders"),
    ("Variational Autoencoders", "GANs"),
    ("Variational Autoencoders", "Diffusion Models"),

    # Neural paths
    ("Neural Networks", "CNNs"),
    ("Neural Networks", "RNNs"),
    ("Neural Networks", "Batch Normalization"),
    ("Neural Networks", "Dropout"),
    ("Neural Networks", "Optimizers (Adam/SGD)"),
    ("Neural Networks", "Reinforcement Learning"),
    ("Neural Networks", "Graph Neural Networks"),
    ("RNNs", "LSTMs"),
    ("RNNs", "GRUs"),
    ("LSTMs", "Attention Mechanism"),
    ("GRUs", "Attention Mechanism"),
    ("Attention Mechanism", "Transformers"),
    ("CNNs", "Residual Networks"),
    ("CNNs", "Vision Transformers"),
    ("Residual Networks", "Vision Transformers"),

    # Advanced
    ("Transformers", "BERT / GPT"),
    ("Transformers", "Diffusion Models"),
    ("Transformers", "LLM Fine-tuning"),
    ("Transformers", "Multimodal Models"),
    ("Vision Transformers", "Multimodal Models"),
    ("BERT / GPT", "LLM Fine-tuning"),
    ("BERT / GPT", "RLHF"),
    ("BERT / GPT", "RAG"),
    ("LLM Fine-tuning", "RLHF"),
    ("LLM Fine-tuning", "AI Agents"),
    ("RAG", "AI Agents"),
    ("Reinforcement Learning", "Policy Gradient"),
    ("Reinforcement Learning", "RLHF"),
    ("Reinforcement Learning", "Meta-Learning"),
    ("Policy Gradient", "RLHF"),
    ("Self-Supervised Learning", "Contrastive Learning"),
    ("Self-Supervised Learning", "BERT / GPT"),
    ("Contrastive Learning", "Multimodal Models"),
    ("Neural Networks", "Self-Supervised Learning"),
    ("Autoencoders", "Self-Supervised Learning"),

    # Expert
    ("Neural Networks", "Neural Architecture Search"),
    ("Neural Networks", "Federated Learning"),
    ("Neural Networks", "Quantization & Pruning"),
    ("RLHF", "AI Agents"),
    ("Meta-Learning", "Neural Architecture Search"),
]

CATEGORY_COLORS = {
    "foundation":   "#1a6985",
    "core":         "#c17d1a",
    "supervised":   "#2d8a4e",
    "unsupervised": "#7b3fa0",
    "ensemble":     "#1a7a6b",
    "neural":       "#1a4da0",
    "advanced":     "#a01a1a",
}
