"""ML Knowledge Graph — ~700 nodes across 7 levels."""

NODES = {
    # ── Level 0: Foundations ──────────────────────────────────────────────
    "Linear Algebra":              (0, "foundation"),
    "Calculus":                    (0, "foundation"),
    "Probability & Stats":         (0, "foundation"),
    "Python":                      (0, "foundation"),
    "Information Theory":          (0, "foundation"),
    "Optimization Theory":         (0, "foundation"),
    "Numerical Methods":           (0, "foundation"),
    "Set Theory":                  (0, "foundation"),
    "Graph Theory":                (0, "foundation"),
    "Linear Programming":          (0, "foundation"),
    "Dynamic Programming":         (0, "foundation"),
    "Matrix Decomposition":        (0, "foundation"),
    "Fourier Analysis":            (0, "foundation"),
    "Stochastic Processes":        (0, "foundation"),
    "Bayesian Statistics":         (0, "foundation"),
    "Hypothesis Testing":          (0, "foundation"),
    "Convex Optimization":         (0, "foundation"),
    "SQL & Databases":             (0, "foundation"),
    "Data Structures":             (0, "foundation"),
    "Game Theory":                 (0, "foundation"),
    "Complex Analysis":            (0, "foundation"),
    "Real Analysis":               (0, "foundation"),
    "Topology":                    (0, "foundation"),
    "Measure Theory":              (0, "foundation"),
    "Monte Carlo Methods":         (0, "foundation"),
    "Markov Chains":               (0, "foundation"),
    "Signal Processing":           (0, "foundation"),
    "Control Theory":              (0, "foundation"),
    "Information Retrieval":       (0, "foundation"),
    "Combinatorics":               (0, "foundation"),
    "Algorithms":                  (0, "foundation"),
    "Complexity Theory":           (0, "foundation"),
    "Statistics (Frequentist)":    (0, "foundation"),
    "Multivariate Calculus":       (0, "foundation"),
    "Differential Equations":      (0, "foundation"),

    # ── Level 1: Core ML Concepts ─────────────────────────────────────────
    "Loss Functions":              (1, "core"),
    "Gradient Descent":            (1, "core"),
    "Backpropagation":             (1, "core"),
    "Regularization":              (1, "core"),
    "Feature Engineering":         (1, "core"),
    "Cross-Validation":            (1, "core"),
    "Bias-Variance Tradeoff":      (1, "core"),
    "Hyperparameter Tuning":       (1, "core"),
    "Data Preprocessing":          (1, "core"),
    "Evaluation Metrics":          (1, "core"),
    "Overfitting":                 (1, "core"),
    "Underfitting":                (1, "core"),
    "Learning Rate Scheduling":    (1, "core"),
    "Early Stopping":              (1, "core"),
    "Data Augmentation":           (1, "core"),
    "Transfer Learning":           (1, "core"),
    "Imbalanced Data":             (1, "core"),
    "Missing Data Imputation":     (1, "core"),
    "Feature Selection":           (1, "core"),
    "Model Selection":             (1, "core"),
    "Pipeline Design":             (1, "core"),
    "Normalization":               (1, "core"),
    "Cross-Entropy Loss":          (1, "core"),
    "KL Divergence":               (1, "core"),
    "Contrastive Loss":            (1, "core"),
    "Stratified Sampling":         (1, "core"),
    "Class Weights":               (1, "core"),
    "Bootstrapping":               (1, "core"),
    "Dimensionality Reduction":    (1, "core"),
    "Curse of Dimensionality":     (1, "core"),
    "No Free Lunch Theorem":       (1, "core"),
    "Maximum Likelihood":          (1, "core"),
    "MAP Estimation":              (1, "core"),
    "EM Algorithm":                (1, "core"),
    "Expectation Maximization":    (1, "core"),
    "Covariate Shift":             (1, "core"),
    "Distribution Shift":          (1, "core"),
    "Label Smoothing":             (1, "core"),
    "Mixup Augmentation":          (1, "core"),
    "CutMix":                      (1, "core"),
    "Focal Loss":                  (1, "core"),
    "Triplet Loss":                (1, "core"),
    "Huber Loss":                  (1, "core"),
    "Cosine Similarity":           (1, "core"),

    # Gradient Descent variants (level 2)
    "Batch Gradient Descent":      (2, "core"),
    "Stochastic Gradient Descent": (2, "core"),
    "Mini-batch Gradient Descent": (2, "core"),
    "Momentum (SGD)":              (2, "core"),
    "Nesterov Accelerated Gradient": (2, "core"),

    # ── Level 2: Classical Supervised ─────────────────────────────────────
    "Linear Regression":           (2, "supervised"),
    "Logistic Regression":         (2, "supervised"),
    "Decision Trees":              (2, "supervised"),
    "SVM":                         (2, "supervised"),
    "k-NN":                        (2, "supervised"),
    "Naive Bayes":                 (2, "supervised"),
    "Ridge & Lasso":               (2, "supervised"),
    "Polynomial Regression":       (2, "supervised"),
    "Elastic Net":                 (2, "supervised"),
    "Perceptron":                  (2, "supervised"),
    "Gaussian Process":            (2, "supervised"),
    "Kernel Methods":              (2, "supervised"),
    "Bayesian Linear Regression":  (2, "supervised"),
    "AdaBoost":                    (2, "supervised"),
    "Multi-task Learning":         (2, "supervised"),
    "Semi-supervised Learning":    (2, "supervised"),
    "Active Learning":             (2, "supervised"),
    "Online Learning":             (2, "supervised"),
    "Label Propagation":           (2, "supervised"),
    "Isotonic Regression":         (2, "supervised"),
    "Quantile Regression":         (2, "supervised"),
    "Survival Analysis":           (2, "supervised"),
    "Poisson Regression":          (2, "supervised"),
    "Ordinal Regression":          (2, "supervised"),
    "Zero-Inflated Models":        (2, "supervised"),
    "Regression Trees":            (2, "supervised"),
    "Prototype Methods":           (2, "supervised"),
    "Fisher Discriminant":         (2, "supervised"),
    "LDA (Linear Discriminant)":   (2, "supervised"),
    "QDA":                         (2, "supervised"),
    "RBF Networks":                (2, "supervised"),
    "Learning Vector Quantization":(2, "supervised"),

    # ── Level 2: Unsupervised ─────────────────────────────────────────────
    "k-Means":                     (2, "unsupervised"),
    "PCA":                         (2, "unsupervised"),
    "DBSCAN":                      (2, "unsupervised"),
    "Gaussian Mixture Models":     (2, "unsupervised"),
    "t-SNE":                       (2, "unsupervised"),
    "UMAP":                        (2, "unsupervised"),
    "ICA":                         (2, "unsupervised"),
    "NMF":                         (2, "unsupervised"),
    "Spectral Clustering":         (2, "unsupervised"),
    "Hierarchical Clustering":     (2, "unsupervised"),
    "OPTICS":                      (2, "unsupervised"),
    "Isolation Forest":            (2, "unsupervised"),
    "One-Class SVM":               (2, "unsupervised"),
    "LOF":                         (2, "unsupervised"),
    "Self-Organizing Maps":        (2, "unsupervised"),
    "Word2Vec":                    (2, "unsupervised"),
    "GloVe":                       (2, "unsupervised"),
    "FastText":                    (2, "unsupervised"),
    "Topic Modeling (LDA)":        (2, "unsupervised"),
    "Matrix Factorization":        (2, "unsupervised"),
    "Collaborative Filtering":     (2, "unsupervised"),
    "HDBSCAN":                     (2, "unsupervised"),
    "Agglomerative Clustering":    (2, "unsupervised"),
    "Mean Shift":                  (2, "unsupervised"),
    "Affinity Propagation":        (2, "unsupervised"),
    "k-Medoids":                   (2, "unsupervised"),
    "BIRCH":                       (2, "unsupervised"),
    "Mini-Batch k-Means":          (2, "unsupervised"),
    "Sparse PCA":                  (2, "unsupervised"),
    "Kernel PCA":                  (2, "unsupervised"),
    "Robust PCA":                  (2, "unsupervised"),

    # ── Level 3: Ensemble ─────────────────────────────────────────────────
    "Bagging":                     (3, "ensemble"),
    "Boosting":                    (3, "ensemble"),
    "Random Forest":               (3, "ensemble"),
    "Gradient Boosting":           (3, "ensemble"),
    "XGBoost":                     (3, "ensemble"),
    "LightGBM":                    (3, "ensemble"),
    "CatBoost":                    (3, "ensemble"),
    "Stacking":                    (3, "ensemble"),
    "Blending":                    (3, "ensemble"),
    "Voting Classifier":           (3, "ensemble"),
    "ExtraTrees":                  (3, "ensemble"),
    "TabNet":                      (3, "ensemble"),
    "DART":                        (3, "ensemble"),
    "Snapshot Ensembles":          (3, "ensemble"),
    "Dropout Ensembles":           (3, "ensemble"),
    "Deep Ensembles":              (3, "ensemble"),
    "Bayesian Model Averaging":    (3, "ensemble"),
    "AdaBoost.R2":                 (3, "ensemble"),
    "HistGradientBoosting":        (3, "ensemble"),
    "NGBoost":                     (3, "ensemble"),
    "Forest of Random Patches":    (3, "ensemble"),

    # ── Level 2-3: Neural Foundations ─────────────────────────────────────
    "Activation Functions":        (2, "neural"),
    "Weight Initialization":       (2, "neural"),
    "Vanishing Gradient":          (2, "neural"),
    "Exploding Gradient":          (2, "neural"),
    "Neural Networks":             (3, "neural"),
    "Batch Normalization":         (3, "neural"),
    "Layer Normalization":         (3, "neural"),
    "Group Normalization":         (3, "neural"),
    "Instance Normalization":      (3, "neural"),
    "Dropout":                     (3, "neural"),
    "Optimizers (Adam/SGD)":       (3, "neural"),
    "Weight Decay":                (3, "neural"),
    "Gradient Clipping":           (3, "neural"),
    "Residual Connections":        (3, "neural"),
    "Skip Connections":            (3, "neural"),
    "Dense Connections":           (3, "neural"),
    "Depthwise Convolution":       (3, "neural"),
    "Dilated Convolution":         (3, "neural"),
    "Transposed Convolution":      (3, "neural"),
    "Pooling Layers":              (3, "neural"),
    "Embedding Layers":            (3, "neural"),
    "Softmax":                     (3, "neural"),
    "ReLU & Variants":             (3, "neural"),
    "GELU":                        (3, "neural"),
    "Swish":                       (3, "neural"),
    "Mish":                        (3, "neural"),

    # ── Level 4: CNNs & Vision ────────────────────────────────────────────
    "CNNs":                        (4, "neural"),
    "Residual Networks":           (4, "neural"),
    "DenseNet":                    (4, "neural"),
    "MobileNet":                   (4, "neural"),
    "EfficientNet":                (4, "neural"),
    "Inception":                   (4, "neural"),
    "U-Net":                       (4, "neural"),
    "YOLO":                        (4, "neural"),
    "R-CNN":                       (4, "neural"),
    "Feature Pyramid Networks":    (4, "neural"),
    "Capsule Networks":            (4, "neural"),
    "Deformable Conv":             (4, "neural"),
    "VGG":                         (4, "neural"),
    "AlexNet":                     (4, "neural"),
    "SqueezeNet":                  (4, "neural"),
    "ShuffleNet":                  (4, "neural"),
    "NASNet":                      (4, "neural"),
    "RegNet":                      (4, "neural"),
    "ConvNeXt":                    (4, "neural"),
    "MaxViT":                      (4, "neural"),
    "Swin Transformer":            (4, "neural"),
    "SegNet":                      (4, "neural"),
    "DeepLab":                     (4, "neural"),
    "Mask R-CNN":                  (4, "neural"),
    "Panoptic Segmentation":       (4, "neural"),
    "Keypoint Detection":          (4, "neural"),
    "Optical Flow":                (4, "neural"),
    "Depth Estimation":            (4, "neural"),
    "Stereo Vision":               (4, "neural"),
    "Point Cloud Networks":        (4, "neural"),
    "3D CNNs":                     (4, "neural"),

    # ── Level 4: RNNs & Sequence ──────────────────────────────────────────
    "RNNs":                        (4, "neural"),
    "LSTMs":                       (4, "neural"),
    "GRUs":                        (4, "neural"),
    "Bidirectional RNN":           (4, "neural"),
    "Seq2Seq":                     (4, "neural"),
    "Attention Mechanism":         (4, "neural"),
    "Multi-Head Attention":        (4, "neural"),
    "Positional Encoding":         (4, "neural"),
    "Temporal Convolutional Net":  (4, "neural"),
    "WaveNet":                     (4, "neural"),
    "Neural Machine Translation":  (4, "neural"),
    "CTC Loss":                    (4, "neural"),
    "Connectionist Models":        (4, "neural"),
    "Echo State Networks":         (4, "neural"),

    # ── Level 4: Graph & Other NNs ────────────────────────────────────────
    "Graph Neural Networks":       (4, "neural"),
    "Graph Attention Networks":    (4, "neural"),
    "Message Passing":             (4, "neural"),
    "Siamese Networks":            (4, "neural"),
    "Hypernetworks":               (4, "neural"),
    "Neural ODEs":                 (4, "neural"),
    "Mixture of Experts":          (4, "neural"),
    "Autoencoders":                (4, "neural"),
    "Sparse Autoencoders":         (4, "neural"),
    "Denoising Autoencoders":      (4, "neural"),
    "Graph Convolutional Networks":(4, "neural"),
    "GraphSAGE":                   (4, "neural"),
    "Node2Vec":                    (4, "neural"),
    "DeepWalk":                    (4, "neural"),
    "Knowledge Graphs":            (4, "neural"),
    "TransE":                      (4, "neural"),

    # ── Level 5: Transformers & LLMs ─────────────────────────────────────
    "LLM":                         (5, "advanced"),
    "Transformers":                (5, "advanced"),
    "BERT":                        (5, "advanced"),
    "GPT":                         (5, "advanced"),
    "T5":                          (5, "advanced"),
    "Vision Transformers":         (5, "advanced"),
    "CLIP":                        (5, "advanced"),
    "BPE Tokenization":            (5, "advanced"),
    "Flash Attention":             (5, "advanced"),
    "Rotary Embeddings":           (5, "advanced"),
    "Sparse Attention":            (5, "advanced"),
    "Feed-Forward Networks":       (5, "advanced"),
    "Mixture of Experts (MoE)":    (5, "advanced"),
    "RoBERTa":                     (5, "advanced"),
    "XLNet":                       (5, "advanced"),
    "ALBERT":                      (5, "advanced"),
    "DistilBERT":                  (5, "advanced"),
    "DeBERTa":                     (5, "advanced"),
    "ELECTRA":                     (5, "advanced"),
    "Longformer":                  (5, "advanced"),
    "BigBird":                     (5, "advanced"),
    "Reformer":                    (5, "advanced"),
    "Perceiver":                   (5, "advanced"),
    "Mamba":                       (5, "advanced"),
    "RetNet":                      (5, "advanced"),
    "RWKV":                        (5, "advanced"),
    "Hyena":                       (5, "advanced"),
    "State Space Models":          (5, "advanced"),
    "Linear Attention":            (5, "advanced"),
    "ALiBi":                       (5, "advanced"),
    "RoPE":                        (5, "advanced"),
    "Sinusoidal Embeddings":       (5, "advanced"),
    "Grouped Query Attention":     (5, "advanced"),
    "Multi-Query Attention":       (5, "advanced"),
    "Sliding Window Attention":    (5, "advanced"),
    "Cross-Attention":             (5, "advanced"),

    # ── Level 5: Generative Models ────────────────────────────────────────
    "GANs":                        (5, "advanced"),
    "VAE":                         (5, "advanced"),
    "Diffusion Models":            (5, "unsupervised"),
    "Score Matching":              (5, "unsupervised"),
    "Flow Models":                 (5, "unsupervised"),
    "Energy-Based Models":         (5, "unsupervised"),
    "DALL-E / Stable Diffusion":   (5, "advanced"),
    "VideoGen":                    (5, "advanced"),
    "Text-to-Speech":              (5, "advanced"),
    "Speech Recognition":          (5, "advanced"),
    "StyleGAN":                    (5, "advanced"),
    "CycleGAN":                    (5, "advanced"),
    "Pix2Pix":                     (5, "advanced"),
    "ControlNet":                  (5, "advanced"),
    "DDPM":                        (5, "unsupervised"),
    "DDIM":                        (5, "unsupervised"),
    "Latent Diffusion":            (5, "unsupervised"),
    "Consistency Models":          (5, "unsupervised"),
    "Flow Matching":               (5, "unsupervised"),
    "Rectified Flow":              (5, "unsupervised"),
    "VQ-VAE":                      (5, "advanced"),
    "VQGAN":                       (5, "advanced"),
    "Tokenization (Images)":       (5, "advanced"),
    "Audio Generation":            (5, "advanced"),
    "Music Generation":            (5, "advanced"),

    # ── Level 5: Representation Learning ─────────────────────────────────
    "Self-Supervised Learning":    (5, "unsupervised"),
    "Contrastive Learning":        (5, "unsupervised"),
    "SimCLR":                      (5, "unsupervised"),
    "MoCo":                        (5, "unsupervised"),
    "DINO":                        (5, "unsupervised"),
    "MAE":                         (5, "unsupervised"),
    "Word Embeddings":             (5, "advanced"),
    "Sentence Embeddings":         (5, "advanced"),
    "Multimodal Models":           (5, "advanced"),
    "BYOL":                        (5, "unsupervised"),
    "VICReg":                      (5, "unsupervised"),
    "Barlow Twins":                (5, "unsupervised"),
    "I-JEPA":                      (5, "unsupervised"),
    "V-JEPA":                      (5, "unsupervised"),
    "BEiT":                        (5, "advanced"),
    "DINOv2":                      (5, "unsupervised"),
    "SigLIP":                      (5, "advanced"),
    "LLaVA":                       (5, "advanced"),
    "Flamingo":                    (5, "advanced"),
    "ImageBind":                   (5, "advanced"),

    # ── Level 5: Reinforcement Learning ──────────────────────────────────
    "Reinforcement Learning":      (5, "advanced"),
    "Policy Gradient":             (5, "advanced"),
    "Q-Learning":                  (5, "advanced"),
    "DQN":                         (5, "advanced"),
    "PPO":                         (5, "advanced"),
    "SAC":                         (5, "advanced"),
    "A3C":                         (5, "advanced"),
    "Model-Based RL":              (5, "advanced"),
    "Offline RL":                  (5, "advanced"),
    "Multi-Agent RL":              (5, "advanced"),
    "Imitation Learning":          (5, "advanced"),
    "Inverse RL":                  (5, "advanced"),
    "TD3":                         (5, "advanced"),
    "DDPG":                        (5, "advanced"),
    "Rainbow DQN":                 (5, "advanced"),
    "MuZero":                      (5, "advanced"),
    "AlphaZero":                   (5, "advanced"),
    "Dreamer":                     (5, "advanced"),
    "World Models RL":             (5, "advanced"),
    "Reward Shaping":              (5, "advanced"),
    "Curiosity-Driven Exploration":(5, "advanced"),
    "Hierarchical RL":             (5, "advanced"),
    "Option Framework":            (5, "advanced"),
    "Multi-Task RL":               (5, "advanced"),
    "Transfer in RL":              (5, "advanced"),

    # ── Level 5: NLP Applications ─────────────────────────────────────────
    "Named Entity Recognition":    (5, "advanced"),
    "Question Answering":          (5, "advanced"),
    "Machine Translation":         (5, "advanced"),
    "Summarization":               (5, "advanced"),
    "Code Generation":             (5, "advanced"),
    "Information Extraction":      (5, "advanced"),
    "Sentiment Analysis":          (5, "advanced"),
    "Text Classification":         (5, "advanced"),
    "Coreference Resolution":      (5, "advanced"),
    "Relation Extraction":         (5, "advanced"),
    "Dependency Parsing":          (5, "advanced"),
    "POS Tagging":                 (5, "advanced"),
    "Text Generation":             (5, "advanced"),
    "Dialogue Systems":            (5, "advanced"),
    "Reading Comprehension":       (5, "advanced"),
    "Open Domain QA":              (5, "advanced"),
    "Semantic Parsing":            (5, "advanced"),
    "Cross-Lingual Transfer":      (5, "advanced"),
    "Slot Filling":                (5, "advanced"),
    "Intent Detection":            (5, "advanced"),

    # ── Level 6: Expert / Cutting Edge ───────────────────────────────────
    "LLM Fine-tuning":             (6, "advanced"),
    "LoRA":                        (6, "advanced"),
    "QLoRA":                       (6, "advanced"),
    "Prefix Tuning":               (6, "advanced"),
    "Prompt Engineering":          (6, "advanced"),
    "RLHF":                        (6, "advanced"),
    "Constitutional AI":           (6, "advanced"),
    "Chain-of-Thought":            (6, "advanced"),
    "ReAct":                       (6, "advanced"),
    "Tool Use":                    (6, "advanced"),
    "AI Agents":                   (6, "advanced"),
    "RAG":                         (6, "advanced"),
    "Memory Systems":              (6, "advanced"),
    "Multi-Agent Systems":         (6, "advanced"),
    "Meta-Learning":               (6, "supervised"),
    "Few-Shot Learning":           (6, "supervised"),
    "Zero-Shot Learning":          (6, "supervised"),
    "Neural Architecture Search":  (6, "advanced"),
    "AutoML":                      (6, "advanced"),
    "Federated Learning":          (6, "supervised"),
    "Differential Privacy":        (6, "advanced"),
    "Quantization & Pruning":      (6, "advanced"),
    "Post-Training Quantization":  (6, "advanced"),
    "Quantization-Aware Training": (6, "advanced"),
    "GPTQ":                        (6, "advanced"),
    "AWQ":                         (6, "advanced"),
    "GGUF":                        (6, "advanced"),
    "Model Inference":             (5, "advanced"),
    "Knowledge Distillation":      (6, "supervised"),
    "Sparse Models":               (6, "advanced"),
    "NeRF":                        (6, "advanced"),
    "3D Gaussian Splatting":       (6, "advanced"),
    "AlphaFold":                   (6, "advanced"),
    "World Models":                (6, "advanced"),
    "Causal ML":                   (6, "supervised"),
    "Interpretability":            (6, "advanced"),
    "SHAP":                        (6, "advanced"),
    "LIME":                        (6, "advanced"),
    "Conformal Prediction":        (6, "supervised"),
    "AI Safety":                   (6, "advanced"),
    "Alignment":                   (6, "advanced"),
    "MLOps":                       (6, "advanced"),
    "Model Monitoring":            (6, "advanced"),
    "Feature Stores":              (6, "advanced"),
    "Experiment Tracking":         (6, "advanced"),
    "Edge AI":                     (6, "advanced"),
    "TensorRT / ONNX":             (6, "advanced"),
    "Adapter Layers":              (6, "advanced"),
    "P-Tuning":                    (6, "advanced"),
    "Instruction Tuning":          (6, "advanced"),
    "DPO":                         (6, "advanced"),
    "PPO for LLMs":                (6, "advanced"),
    "Reward Modeling":             (6, "advanced"),
    "Speculative Decoding":        (6, "advanced"),
    "FlashAttention-2":            (6, "advanced"),
    "Continuous Batching":         (6, "advanced"),
    "vLLM":                        (6, "advanced"),
    "LLM Serving":                 (6, "advanced"),
    "Model Parallelism":           (6, "advanced"),
    "Pipeline Parallelism":        (6, "advanced"),
    "Tensor Parallelism":          (6, "advanced"),
    "ZeRO Optimization":           (6, "advanced"),
    "Mixed Precision Training":    (6, "advanced"),
    "Gradient Checkpointing":      (6, "advanced"),
    "DeepSpeed":                   (6, "advanced"),
    "FSDP":                        (6, "advanced"),
    "Mixture of Agents":           (6, "advanced"),
    "Agentic Workflows":           (6, "advanced"),
    "Long Context LLMs":           (6, "advanced"),
    "Retrieval Augmented Training":(6, "advanced"),
    "Grounded Generation":         (6, "advanced"),
    "Hallucination Detection":     (6, "advanced"),
    "Uncertainty Quantification":  (6, "advanced"),
    "Bayesian Deep Learning":      (6, "advanced"),
    "Neural Scaling Laws":         (6, "advanced"),
    "Emergent Abilities":          (6, "advanced"),
    "In-Context Learning":         (6, "advanced"),
    "Mechanistic Interpretability":(6, "advanced"),
    "Superposition (AI)":          (6, "advanced"),
    "Sparse Features":             (6, "advanced"),
    "Model Editing":               (6, "advanced"),
    "Unlearning":                  (6, "advanced"),
    "Watermarking AI":             (6, "advanced"),
    "AI Governance":               (6, "advanced"),
    "Responsible AI":              (6, "advanced"),
    "Bias in ML":                  (6, "advanced"),
    "Fairness in ML":              (6, "advanced"),
    "Robustness":                  (6, "advanced"),
    "Adversarial Attacks":         (6, "advanced"),
    "Adversarial Training":        (6, "advanced"),
    "Certified Robustness":        (6, "advanced"),
    "Data-Centric AI":             (6, "advanced"),
    "Synthetic Data":              (6, "advanced"),
    "Active Data Collection":      (6, "advanced"),
    "Foundation Models":           (6, "advanced"),

    # DeepSeek research
    "DeepSeek-V3":                 (6, "advanced"),
    "DeepSeek-R1":                 (6, "advanced"),
    "DeepSeekMoE":                 (6, "advanced"),
    "Multi-head Latent Attention": (6, "advanced"),
    "Multi-Token Prediction":      (6, "advanced"),
    "FP8 Training":                (6, "advanced"),
    "DualPipe":                    (6, "advanced"),
    "Expert Parallelism":          (6, "advanced"),
    "Aletheia":                    (6, "advanced"),

    # Karpathy's teachings
    "Autograd":                    (1, "core"),
    "Character-level LM":          (3, "neural"),
    "Bigram Language Model":       (2, "core"),

    "Generalist Agents":           (6, "advanced"),
    "Embodied AI":                 (6, "advanced"),
    "Robotics Learning":           (6, "advanced"),
    "Sim-to-Real Transfer":        (6, "advanced"),
    "Continual Learning":          (6, "supervised"),
    "Catastrophic Forgetting":     (6, "advanced"),
    "Elastic Weight Consolidation":(6, "advanced"),
    "Progressive Neural Networks": (6, "neural"),
    "Hyperparameter-Free Methods": (6, "advanced"),
    "Neural Tangent Kernel":       (6, "advanced"),
    "Double Descent":              (6, "advanced"),
    "Grokking":                    (6, "advanced"),
    "Scaling Laws":                (6, "advanced"),
}

EDGES = [
    # LLM
    ("Transformers", "LLM"), ("Self-Supervised Learning", "LLM"),
    ("Transfer Learning", "LLM"), ("Neural Scaling Laws", "LLM"),
    ("LLM", "RLHF"), ("LLM", "LLM Fine-tuning"), ("LLM", "RAG"),
    ("LLM", "Chain-of-Thought"), ("LLM", "In-Context Learning"),
    ("LLM", "Foundation Models"), ("LLM", "Instruction Tuning"),
    ("LLM", "LoRA"), ("LLM", "Prompt Engineering"),
    # Foundations → Core
    ("Linear Algebra", "Gradient Descent"), ("Linear Algebra", "PCA"),
    ("Linear Algebra", "SVM"), ("Linear Algebra", "Neural Networks"),
    ("Linear Algebra", "Matrix Decomposition"), ("Linear Algebra", "NMF"),
    ("Calculus", "Gradient Descent"), ("Calculus", "Backpropagation"),
    ("Calculus", "Optimization Theory"), ("Calculus", "Neural ODEs"),
    ("Calculus", "Differential Equations"),
    ("Probability & Stats", "Loss Functions"), ("Probability & Stats", "Naive Bayes"),
    ("Probability & Stats", "Gaussian Mixture Models"), ("Probability & Stats", "Bayesian Statistics"),
    ("Probability & Stats", "Hypothesis Testing"), ("Probability & Stats", "Gaussian Process"),
    ("Probability & Stats", "Monte Carlo Methods"), ("Probability & Stats", "Maximum Likelihood"),
    ("Information Theory", "Loss Functions"), ("Information Theory", "Cross-Entropy Loss"),
    ("Information Theory", "KL Divergence"), ("Information Theory", "Evaluation Metrics"),
    ("Optimization Theory", "Gradient Descent"), ("Optimization Theory", "Convex Optimization"),
    ("Optimization Theory", "Optimizers (Adam/SGD)"),
    ("Numerical Methods", "Gradient Descent"), ("Numerical Methods", "Neural Networks"),
    ("Python", "Feature Engineering"), ("Python", "Data Preprocessing"), ("Python", "Pipeline Design"),
    ("Graph Theory", "Graph Neural Networks"), ("Graph Theory", "Message Passing"),
    ("Graph Theory", "Knowledge Graphs"),

    # DeepSeek research edges
    ("Mixture of Experts", "DeepSeekMoE"),
    ("DeepSeekMoE", "DeepSeek-V3"), ("Multi-head Latent Attention", "DeepSeek-V3"),
    ("Multi-Token Prediction", "DeepSeek-V3"), ("FP8 Training", "DeepSeek-V3"),
    ("DeepSeek-V3", "DeepSeek-R1"),
    ("Reinforcement Learning", "DeepSeek-R1"), ("Chain-of-Thought", "DeepSeek-R1"),
    ("Knowledge Distillation", "DeepSeek-R1"),
    ("Multi-Head Attention", "Multi-head Latent Attention"),
    ("Flash Attention", "Multi-head Latent Attention"),
    ("Grouped Query Attention", "Multi-head Latent Attention"),
    ("LLM", "Multi-Token Prediction"), ("Speculative Decoding", "Multi-Token Prediction"),
    ("Mixed Precision Training", "FP8 Training"), ("Quantization & Pruning", "FP8 Training"),
    ("Pipeline Parallelism", "DualPipe"), ("DeepSeek-V3", "DualPipe"),
    ("Mixture of Experts", "Expert Parallelism"), ("Model Parallelism", "Expert Parallelism"),
    ("DeepSeek-V3", "Expert Parallelism"),
    ("LLM", "Aletheia"), ("AI Agents", "Aletheia"),
    ("Chain-of-Thought", "Aletheia"),
    ("Bayesian Statistics", "Bayesian Linear Regression"), ("Bayesian Statistics", "Gaussian Process"),
    ("Bayesian Statistics", "MAP Estimation"), ("Bayesian Statistics", "EM Algorithm"),
    ("Stochastic Processes", "Reinforcement Learning"), ("Stochastic Processes", "Diffusion Models"),
    ("Stochastic Processes", "Markov Chains"),
    ("Convex Optimization", "SVM"), ("Matrix Decomposition", "PCA"),
    ("Signal Processing", "Fourier Analysis"), ("Signal Processing", "WaveNet"),
    ("Control Theory", "Reinforcement Learning"),
    ("Markov Chains", "Reinforcement Learning"), ("Markov Chains", "Q-Learning"),
    ("Monte Carlo Methods", "MCTS"), ("Monte Carlo Methods", "Offline RL"),
    ("Maximum Likelihood", "EM Algorithm"), ("Maximum Likelihood", "VAE"),
    ("EM Algorithm", "Gaussian Mixture Models"),

    # Karpathy's teachings edges
    ("Calculus", "Autograd"), ("Autograd", "Backpropagation"),
    ("Autograd", "Neural Networks"),
    ("Probability & Stats", "Bigram Language Model"), ("Bigram Language Model", "Character-level LM"),
    ("Character-level LM", "RNNs"), ("Character-level LM", "LSTMs"),
    ("Bigram Language Model", "Word Embeddings"),

    # Core → supervised/unsupervised
    ("Loss Functions", "Linear Regression"), ("Loss Functions", "Logistic Regression"),
    ("Loss Functions", "Neural Networks"), ("Loss Functions", "Cross-Entropy Loss"),
    ("Loss Functions", "Focal Loss"), ("Loss Functions", "Triplet Loss"),
    ("Gradient Descent", "Linear Regression"), ("Gradient Descent", "Neural Networks"),
    ("Gradient Descent", "Gradient Boosting"), ("Gradient Descent", "Learning Rate Scheduling"),
    ("Gradient Descent", "Batch Gradient Descent"), ("Gradient Descent", "Stochastic Gradient Descent"),
    ("Gradient Descent", "Mini-batch Gradient Descent"),
    ("Stochastic Gradient Descent", "Momentum (SGD)"),
    ("Momentum (SGD)", "Nesterov Accelerated Gradient"),
    ("Stochastic Gradient Descent", "Optimizers (Adam/SGD)"),
    ("Momentum (SGD)", "Optimizers (Adam/SGD)"),
    ("Nesterov Accelerated Gradient", "Optimizers (Adam/SGD)"),
    ("Backpropagation", "Neural Networks"), ("Backpropagation", "Vanishing Gradient"),
    ("Backpropagation", "Exploding Gradient"),
    ("Regularization", "Ridge & Lasso"), ("Regularization", "Dropout"),
    ("Regularization", "Batch Normalization"), ("Regularization", "Weight Decay"),
    ("Regularization", "Early Stopping"),
    ("Bias-Variance Tradeoff", "Regularization"), ("Bias-Variance Tradeoff", "Cross-Validation"),
    ("Bias-Variance Tradeoff", "Overfitting"), ("Bias-Variance Tradeoff", "Underfitting"),
    ("Cross-Validation", "Hyperparameter Tuning"), ("Cross-Validation", "Model Selection"),
    ("Feature Engineering", "Linear Regression"), ("Feature Engineering", "Feature Selection"),
    ("Feature Engineering", "Dimensionality Reduction"),
    ("Data Preprocessing", "Feature Engineering"), ("Data Preprocessing", "Normalization"),
    ("Data Preprocessing", "Missing Data Imputation"),
    ("Evaluation Metrics", "Cross-Validation"), ("Evaluation Metrics", "Model Selection"),
    ("Transfer Learning", "LLM Fine-tuning"), ("Transfer Learning", "BERT"),
    ("Transfer Learning", "CNNs"), ("Transfer Learning", "Foundation Models"),
    ("KL Divergence", "VAE"), ("KL Divergence", "Diffusion Models"),
    ("Contrastive Loss", "Contrastive Learning"), ("Contrastive Loss", "SimCLR"),
    ("Triplet Loss", "Siamese Networks"), ("Triplet Loss", "Contrastive Learning"),
    ("Dimensionality Reduction", "PCA"), ("Dimensionality Reduction", "t-SNE"),
    ("Dimensionality Reduction", "UMAP"),
    ("Maximum Likelihood", "Logistic Regression"), ("Maximum Likelihood", "Gaussian Process"),
    ("MAP Estimation", "Bayesian Linear Regression"), ("MAP Estimation", "Naive Bayes"),
    ("Label Smoothing", "Cross-Entropy Loss"), ("Focal Loss", "R-CNN"),
    ("Data Augmentation", "CNNs"), ("Data Augmentation", "Mixup Augmentation"),
    ("Mixup Augmentation", "CutMix"),

    # Supervised
    ("Linear Regression", "Ridge & Lasso"), ("Linear Regression", "Polynomial Regression"),
    ("Linear Regression", "Bayesian Linear Regression"), ("Linear Regression", "Elastic Net"),
    ("Logistic Regression", "Multi-task Learning"), ("Logistic Regression", "LDA (Linear Discriminant)"),
    ("Decision Trees", "Random Forest"), ("Decision Trees", "Gradient Boosting"),
    ("Decision Trees", "Bagging"), ("Decision Trees", "Boosting"), ("Decision Trees", "ExtraTrees"),
    ("Decision Trees", "Regression Trees"),
    ("Bagging", "Random Forest"), ("Boosting", "Gradient Boosting"), ("Boosting", "AdaBoost"),
    ("AdaBoost", "Gradient Boosting"), ("AdaBoost", "AdaBoost.R2"),
    ("Gradient Boosting", "XGBoost"), ("Gradient Boosting", "LightGBM"),
    ("Gradient Boosting", "CatBoost"), ("Gradient Boosting", "DART"),
    ("Gradient Boosting", "HistGradientBoosting"), ("Gradient Boosting", "NGBoost"),
    ("Random Forest", "Stacking"), ("XGBoost", "Stacking"), ("XGBoost", "TabNet"),
    ("Stacking", "Blending"), ("Stacking", "Voting Classifier"),
    ("Perceptron", "Neural Networks"),
    ("Kernel Methods", "SVM"), ("Kernel Methods", "Gaussian Process"), ("Kernel Methods", "Kernel PCA"),
    ("Semi-supervised Learning", "Self-Supervised Learning"), ("Semi-supervised Learning", "Label Propagation"),
    ("Active Learning", "Semi-supervised Learning"),
    ("Gaussian Process", "Bayesian Deep Learning"),
    ("LDA (Linear Discriminant)", "QDA"),

    # Unsupervised
    ("k-Means", "DBSCAN"), ("k-Means", "OPTICS"), ("k-Means", "Spectral Clustering"),
    ("k-Means", "Mini-Batch k-Means"), ("k-Means", "k-Medoids"),
    ("PCA", "t-SNE"), ("PCA", "UMAP"), ("PCA", "ICA"), ("PCA", "NMF"),
    ("PCA", "Sparse PCA"), ("PCA", "Robust PCA"),
    ("Gaussian Mixture Models", "Isolation Forest"), ("Gaussian Mixture Models", "LOF"),
    ("Word2Vec", "GloVe"), ("Word2Vec", "FastText"), ("Word2Vec", "Word Embeddings"),
    ("Word2Vec", "Sentence Embeddings"), ("Word2Vec", "Node2Vec"),
    ("Matrix Factorization", "Collaborative Filtering"),
    ("Hierarchical Clustering", "Agglomerative Clustering"), ("DBSCAN", "HDBSCAN"),
    ("Spectral Clustering", "Graph Neural Networks"),
    ("ICA", "Signal Processing"), ("NMF", "Topic Modeling (LDA)"),

    # Neural foundations
    ("Activation Functions", "Neural Networks"), ("Activation Functions", "Vanishing Gradient"),
    ("Activation Functions", "ReLU & Variants"), ("Activation Functions", "GELU"),
    ("ReLU & Variants", "Swish"), ("Swish", "Mish"), ("GELU", "Transformers"),
    ("Weight Initialization", "Vanishing Gradient"),
    ("Vanishing Gradient", "LSTMs"), ("Vanishing Gradient", "Residual Connections"),
    ("Exploding Gradient", "Gradient Clipping"),
    ("Residual Connections", "Residual Networks"), ("Residual Connections", "DenseNet"),
    ("Residual Connections", "Skip Connections"),
    ("Skip Connections", "U-Net"),
    ("Dense Connections", "DenseNet"),
    ("Batch Normalization", "Residual Networks"), ("Batch Normalization", "Layer Normalization"),
    ("Layer Normalization", "Transformers"), ("Layer Normalization", "Group Normalization"),
    ("Optimizers (Adam/SGD)", "Learning Rate Scheduling"),
    ("Depthwise Convolution", "MobileNet"), ("Dilated Convolution", "DeepLab"),
    ("Transposed Convolution", "U-Net"), ("Transposed Convolution", "GANs"),
    ("Embedding Layers", "Word2Vec"), ("Embedding Layers", "Transformers"),
    ("Softmax", "Logistic Regression"), ("Softmax", "Attention Mechanism"),
    ("Pooling Layers", "CNNs"),

    # Neural networks → everything
    ("Neural Networks", "CNNs"), ("Neural Networks", "RNNs"),
    ("Neural Networks", "Batch Normalization"), ("Neural Networks", "Dropout"),
    ("Neural Networks", "Optimizers (Adam/SGD)"),
    ("Neural Networks", "Reinforcement Learning"), ("Neural Networks", "Graph Neural Networks"),
    ("Neural Networks", "Autoencoders"), ("Neural Networks", "Self-Supervised Learning"),
    ("Neural Networks", "Siamese Networks"), ("Neural Networks", "Neural ODEs"),
    ("Neural Networks", "Mixture of Experts"), ("Neural Networks", "Hypernetworks"),
    ("Neural Networks", "Neural Architecture Search"), ("Neural Networks", "Federated Learning"),
    ("Neural Networks", "Quantization & Pruning"), ("Neural Networks", "Knowledge Distillation"),
    ("Neural Networks", "Bayesian Deep Learning"), ("Neural Networks", "Adversarial Attacks"),
    ("Neural Networks", "Deep Ensembles"),

    # CNN family
    ("CNNs", "Residual Networks"), ("CNNs", "DenseNet"), ("CNNs", "MobileNet"),
    ("CNNs", "EfficientNet"), ("CNNs", "Inception"), ("CNNs", "U-Net"),
    ("CNNs", "YOLO"), ("CNNs", "R-CNN"), ("CNNs", "Feature Pyramid Networks"),
    ("CNNs", "Capsule Networks"), ("CNNs", "Deformable Conv"),
    ("CNNs", "Vision Transformers"), ("CNNs", "VGG"), ("CNNs", "AlexNet"),
    ("CNNs", "SqueezeNet"), ("CNNs", "ShuffleNet"), ("CNNs", "NASNet"),
    ("CNNs", "RegNet"), ("CNNs", "ConvNeXt"), ("CNNs", "Swin Transformer"),
    ("CNNs", "SegNet"), ("CNNs", "DeepLab"), ("CNNs", "3D CNNs"),
    ("Residual Networks", "Vision Transformers"), ("Residual Networks", "EfficientNet"),
    ("Residual Networks", "ConvNeXt"), ("Residual Networks", "RegNet"),
    ("Feature Pyramid Networks", "YOLO"), ("Feature Pyramid Networks", "R-CNN"),
    ("Feature Pyramid Networks", "Mask R-CNN"),
    ("R-CNN", "Mask R-CNN"), ("YOLO", "Keypoint Detection"),
    ("Mask R-CNN", "Panoptic Segmentation"),
    ("U-Net", "Latent Diffusion"),
    ("MobileNet", "SqueezeNet"), ("MobileNet", "ShuffleNet"),
    ("EfficientNet", "NASNet"), ("Swin Transformer", "MaxViT"),
    ("ConvNeXt", "MaxViT"),
    ("DeepLab", "Panoptic Segmentation"),

    # RNN family
    ("RNNs", "LSTMs"), ("RNNs", "GRUs"), ("RNNs", "Bidirectional RNN"),
    ("RNNs", "Seq2Seq"), ("RNNs", "Temporal Convolutional Net"),
    ("LSTMs", "Attention Mechanism"), ("GRUs", "Attention Mechanism"),
    ("Seq2Seq", "Attention Mechanism"), ("Seq2Seq", "Machine Translation"),
    ("Seq2Seq", "Neural Machine Translation"),
    ("Attention Mechanism", "Multi-Head Attention"), ("Attention Mechanism", "Transformers"),
    ("Attention Mechanism", "Cross-Attention"),
    ("Multi-Head Attention", "Transformers"), ("Multi-Head Attention", "Flash Attention"),
    ("Multi-Head Attention", "Grouped Query Attention"), ("Multi-Head Attention", "Multi-Query Attention"),
    ("Positional Encoding", "Transformers"), ("Positional Encoding", "Rotary Embeddings"),
    ("Positional Encoding", "ALiBi"), ("Positional Encoding", "RoPE"),
    ("WaveNet", "Audio Generation"), ("WaveNet", "Text-to-Speech"),
    ("CTC Loss", "Speech Recognition"),

    # Graph NNs
    ("Graph Neural Networks", "Graph Attention Networks"),
    ("Graph Neural Networks", "Message Passing"), ("Graph Neural Networks", "Graph Convolutional Networks"),
    ("Graph Neural Networks", "GraphSAGE"), ("Graph Neural Networks", "Knowledge Graphs"),
    ("Knowledge Graphs", "TransE"), ("Node2Vec", "DeepWalk"),
    ("DeepWalk", "Node2Vec"),

    # Autoencoders
    ("Autoencoders", "VAE"), ("Autoencoders", "Self-Supervised Learning"),
    ("Autoencoders", "Sparse Autoencoders"), ("Autoencoders", "Denoising Autoencoders"),
    ("VAE", "GANs"), ("VAE", "Diffusion Models"), ("VAE", "Flow Models"), ("VAE", "VQ-VAE"),
    ("Denoising Autoencoders", "Diffusion Models"),

    # Transformers family
    ("Transformers", "BERT"), ("Transformers", "GPT"), ("Transformers", "T5"),
    ("Transformers", "Diffusion Models"), ("Transformers", "LLM Fine-tuning"),
    ("Transformers", "Multimodal Models"), ("Transformers", "Mixture of Experts (MoE)"),
    ("Transformers", "Sparse Attention"), ("Transformers", "Flash Attention"),
    ("Transformers", "State Space Models"), ("Transformers", "Linear Attention"),
    ("Transformers", "RoBERTa"), ("Transformers", "XLNet"), ("Transformers", "ALBERT"),
    ("Transformers", "Longformer"), ("Transformers", "BigBird"), ("Transformers", "Reformer"),
    ("Transformers", "Perceiver"), ("Transformers", "Mamba"),
    ("BERT", "RoBERTa"), ("BERT", "ALBERT"), ("BERT", "DistilBERT"), ("BERT", "DeBERTa"),
    ("BERT", "ELECTRA"), ("BERT", "LLM Fine-tuning"), ("BERT", "RLHF"),
    ("BERT", "Question Answering"), ("BERT", "Named Entity Recognition"),
    ("BERT", "Text Classification"), ("BERT", "Sentiment Analysis"), ("BERT", "Summarization"),
    ("GPT", "LLM Fine-tuning"), ("GPT", "Code Generation"), ("GPT", "Chain-of-Thought"),
    ("GPT", "RLHF"), ("GPT", "RAG"), ("GPT", "In-Context Learning"), ("GPT", "Emergent Abilities"),
    ("T5", "Machine Translation"), ("T5", "Summarization"), ("T5", "Instruction Tuning"),
    ("Vision Transformers", "Multimodal Models"), ("Vision Transformers", "CLIP"),
    ("Vision Transformers", "BEiT"), ("Vision Transformers", "DINOv2"),
    ("Swin Transformer", "Vision Transformers"),
    ("Flash Attention", "FlashAttention-2"),
    ("Mamba", "RetNet"), ("Mamba", "RWKV"), ("Mamba", "Hyena"),
    ("State Space Models", "Mamba"), ("State Space Models", "RetNet"),
    ("LLM Fine-tuning", "LoRA"), ("LLM Fine-tuning", "QLoRA"),
    ("LLM Fine-tuning", "Prefix Tuning"), ("LLM Fine-tuning", "RLHF"),
    ("LLM Fine-tuning", "AI Agents"), ("LLM Fine-tuning", "Adapter Layers"),
    ("LLM Fine-tuning", "P-Tuning"), ("LLM Fine-tuning", "Instruction Tuning"),
    ("LLM Fine-tuning", "DPO"), ("LLM Fine-tuning", "MLOps"),
    ("LoRA", "QLoRA"), ("Instruction Tuning", "RLHF"),
    ("DPO", "RLHF"),

    # Generative
    ("GANs", "DALL-E / Stable Diffusion"), ("GANs", "StyleGAN"), ("GANs", "CycleGAN"),
    ("GANs", "Pix2Pix"), ("GANs", "VQGAN"),
    ("Diffusion Models", "DALL-E / Stable Diffusion"), ("Diffusion Models", "VideoGen"),
    ("Diffusion Models", "Score Matching"), ("Diffusion Models", "DDPM"), ("Diffusion Models", "DDIM"),
    ("Diffusion Models", "Latent Diffusion"), ("Diffusion Models", "Consistency Models"),
    ("Diffusion Models", "ControlNet"), ("Diffusion Models", "Flow Matching"),
    ("DDPM", "DDIM"), ("Latent Diffusion", "DALL-E / Stable Diffusion"),
    ("Latent Diffusion", "ControlNet"),
    ("Score Matching", "Flow Models"), ("Flow Models", "Rectified Flow"),
    ("Flow Matching", "Rectified Flow"),
    ("CLIP", "Multimodal Models"), ("CLIP", "DALL-E / Stable Diffusion"),
    ("CLIP", "SigLIP"), ("CLIP", "LLaVA"),
    ("VQ-VAE", "VQGAN"), ("VQGAN", "Tokenization (Images)"),
    ("Tokenization (Images)", "GPT"),
    ("StyleGAN", "DALL-E / Stable Diffusion"),
    ("Audio Generation", "Music Generation"),

    # Self-supervised / contrastive
    ("Self-Supervised Learning", "Contrastive Learning"), ("Self-Supervised Learning", "MAE"),
    ("Self-Supervised Learning", "DINO"), ("Self-Supervised Learning", "BERT"),
    ("Self-Supervised Learning", "BYOL"), ("Self-Supervised Learning", "VICReg"),
    ("Self-Supervised Learning", "Barlow Twins"), ("Self-Supervised Learning", "I-JEPA"),
    ("Contrastive Learning", "SimCLR"), ("Contrastive Learning", "MoCo"),
    ("Contrastive Learning", "Multimodal Models"), ("Contrastive Learning", "BYOL"),
    ("SimCLR", "DINO"), ("MoCo", "DINO"), ("DINO", "DINOv2"),
    ("Word Embeddings", "Sentence Embeddings"),
    ("BEiT", "MAE"), ("DINOv2", "V-JEPA"), ("I-JEPA", "V-JEPA"),
    ("LLaVA", "Multimodal Models"), ("Flamingo", "Multimodal Models"),
    ("ImageBind", "Multimodal Models"), ("SigLIP", "Multimodal Models"),

    # RL family
    ("Reinforcement Learning", "Policy Gradient"), ("Reinforcement Learning", "Q-Learning"),
    ("Reinforcement Learning", "Model-Based RL"), ("Reinforcement Learning", "Offline RL"),
    ("Reinforcement Learning", "Multi-Agent RL"), ("Reinforcement Learning", "Imitation Learning"),
    ("Reinforcement Learning", "RLHF"), ("Reinforcement Learning", "Meta-Learning"),
    ("Reinforcement Learning", "Hierarchical RL"), ("Reinforcement Learning", "Curiosity-Driven Exploration"),
    ("Reinforcement Learning", "Multi-Task RL"), ("Reinforcement Learning", "Reward Shaping"),
    ("Q-Learning", "DQN"), ("DQN", "Rainbow DQN"),
    ("Policy Gradient", "PPO"), ("Policy Gradient", "A3C"), ("Policy Gradient", "SAC"),
    ("Policy Gradient", "DDPG"), ("Policy Gradient", "TD3"),
    ("PPO", "RLHF"), ("SAC", "Offline RL"),
    ("Imitation Learning", "Inverse RL"),
    ("Model-Based RL", "World Models RL"), ("Model-Based RL", "MuZero"), ("Model-Based RL", "Dreamer"),
    ("MuZero", "AlphaZero"), ("Dreamer", "World Models RL"),
    ("DDPG", "TD3"),
    ("Hierarchical RL", "Option Framework"),

    # NLP applications
    ("BERT", "Coreference Resolution"), ("BERT", "Relation Extraction"),
    ("BERT", "Dependency Parsing"), ("BERT", "POS Tagging"),
    ("GPT", "Text Generation"), ("GPT", "Dialogue Systems"),
    ("T5", "Reading Comprehension"), ("T5", "Open Domain QA"),
    ("Seq2Seq", "Semantic Parsing"), ("BERT", "Slot Filling"), ("BERT", "Intent Detection"),
    ("Cross-Lingual Transfer", "BERT"), ("Cross-Lingual Transfer", "Machine Translation"),

    # Expert level
    ("RLHF", "Constitutional AI"), ("RLHF", "AI Agents"), ("RLHF", "Alignment"),
    ("RLHF", "Reward Modeling"), ("RLHF", "PPO for LLMs"),
    ("Chain-of-Thought", "ReAct"), ("Chain-of-Thought", "AI Agents"),
    ("ReAct", "Tool Use"), ("ReAct", "AI Agents"),
    ("Tool Use", "AI Agents"), ("RAG", "AI Agents"),
    ("AI Agents", "Multi-Agent Systems"), ("AI Agents", "Memory Systems"),
    ("AI Agents", "Agentic Workflows"), ("AI Agents", "Mixture of Agents"),
    ("AI Agents", "Generalist Agents"),
    ("RAG", "Retrieval Augmented Training"), ("RAG", "Grounded Generation"),
    ("Grounded Generation", "Hallucination Detection"),
    ("Meta-Learning", "Few-Shot Learning"), ("Meta-Learning", "Zero-Shot Learning"),
    ("Meta-Learning", "Neural Architecture Search"), ("Meta-Learning", "AutoML"),
    ("Few-Shot Learning", "Zero-Shot Learning"), ("Few-Shot Learning", "In-Context Learning"),
    ("Prompt Engineering", "Chain-of-Thought"), ("Prompt Engineering", "Few-Shot Learning"),
    ("Prompt Engineering", "In-Context Learning"),
    ("Quantization & Pruning", "Knowledge Distillation"),
    ("Quantization & Pruning", "Sparse Models"), ("Quantization & Pruning", "TensorRT / ONNX"),
    ("Quantization & Pruning", "Mixed Precision Training"),
    ("Quantization & Pruning", "Post-Training Quantization"),
    ("Quantization & Pruning", "Quantization-Aware Training"),
    ("Post-Training Quantization", "GPTQ"), ("Post-Training Quantization", "AWQ"),
    ("Post-Training Quantization", "GGUF"),
    ("GPTQ", "vLLM"), ("AWQ", "vLLM"), ("GGUF", "Edge AI"),
    ("Quantization-Aware Training", "Mixed Precision Training"),
    ("Neural Networks", "Model Inference"), ("Model Inference", "LLM Serving"),
    ("Model Inference", "Quantization & Pruning"), ("Model Inference", "TensorRT / ONNX"),
    ("Model Inference", "Edge AI"), ("Model Inference", "Speculative Decoding"),
    ("Knowledge Distillation", "Edge AI"), ("TensorRT / ONNX", "Edge AI"),
    ("Knowledge Distillation", "DistilBERT"),
    ("Federated Learning", "Differential Privacy"),
    ("AlphaFold", "World Models"), ("AlphaFold", "Foundation Models"),
    ("NeRF", "3D Gaussian Splatting"),
    ("Causal ML", "Interpretability"),
    ("Interpretability", "SHAP"), ("Interpretability", "LIME"),
    ("Interpretability", "AI Safety"), ("Interpretability", "Mechanistic Interpretability"),
    ("Mechanistic Interpretability", "Superposition (AI)"), ("Mechanistic Interpretability", "Sparse Features"),
    ("AI Safety", "Alignment"), ("AI Safety", "Constitutional AI"),
    ("AI Safety", "Robustness"), ("AI Safety", "Hallucination Detection"),
    ("MLOps", "Model Monitoring"), ("MLOps", "Feature Stores"),
    ("MLOps", "Experiment Tracking"), ("MLOps", "Edge AI"),
    ("Adversarial Attacks", "Adversarial Training"), ("Adversarial Training", "Certified Robustness"),
    ("Robustness", "Adversarial Attacks"), ("Robustness", "Certified Robustness"),
    ("Model Parallelism", "Pipeline Parallelism"), ("Model Parallelism", "Tensor Parallelism"),
    ("Model Parallelism", "ZeRO Optimization"),
    ("ZeRO Optimization", "DeepSpeed"), ("ZeRO Optimization", "FSDP"),
    ("FlashAttention-2", "Continuous Batching"), ("Continuous Batching", "vLLM"),
    ("vLLM", "LLM Serving"), ("Speculative Decoding", "LLM Serving"),
    ("LLM Fine-tuning", "Speculative Decoding"),
    ("Mixed Precision Training", "DeepSpeed"), ("Gradient Checkpointing", "DeepSpeed"),
    ("Neural Scaling Laws", "Scaling Laws"), ("Scaling Laws", "Emergent Abilities"),
    ("Emergent Abilities", "In-Context Learning"),
    ("Foundation Models", "Generalist Agents"), ("Foundation Models", "Embodied AI"),
    ("Embodied AI", "Robotics Learning"), ("Robotics Learning", "Sim-to-Real Transfer"),
    ("Continual Learning", "Catastrophic Forgetting"),
    ("Catastrophic Forgetting", "Elastic Weight Consolidation"),
    ("Catastrophic Forgetting", "Progressive Neural Networks"),
    ("Data-Centric AI", "Synthetic Data"), ("Data-Centric AI", "Active Data Collection"),
    ("Synthetic Data", "Data Augmentation"),
    ("Bias in ML", "Fairness in ML"), ("Fairness in ML", "Responsible AI"),
    ("Responsible AI", "AI Governance"), ("Responsible AI", "Alignment"),
    ("Model Editing", "Unlearning"), ("Watermarking AI", "AI Governance"),
    ("Double Descent", "Neural Tangent Kernel"), ("Grokking", "Double Descent"),
    ("Uncertainty Quantification", "Bayesian Deep Learning"),
    ("Bayesian Deep Learning", "Conformal Prediction"),
    ("Long Context LLMs", "Flash Attention"), ("Long Context LLMs", "Sliding Window Attention"),
    ("Sliding Window Attention", "Longformer"),
]

CATEGORY_COLORS = {
    "foundation":   "#1a6985",
    "core":         "#c17d1a",
    "supervised":   "#2d8a4e",
    "unsupervised": "#7b3fa0",
    "ensemble":     "#1a7a6b",
    "neural":       "#1a4da0",
    "advanced":     "#a01a1a",
}

# Fix missing node referenced in edges
_extra = [
    ("MCTS", (5, "advanced")),
]
for name, val in _extra:
    if name not in NODES:
        NODES[name] = val
