"""ML Knowledge Graph data — nodes and edges."""

NODES = {
    # label: (level, category)
    "Linear Algebra":           (0, "foundation"),
    "Calculus":                 (0, "foundation"),
    "Probability & Stats":      (0, "foundation"),
    "Python":                   (0, "foundation"),
    "Loss Functions":           (1, "core"),
    "Gradient Descent":         (1, "core"),
    "Backpropagation":          (1, "core"),
    "Regularization":           (1, "core"),
    "Feature Engineering":      (1, "core"),
    "Linear Regression":        (2, "supervised"),
    "Logistic Regression":      (2, "supervised"),
    "Decision Trees":           (2, "supervised"),
    "SVM":                      (2, "supervised"),
    "k-NN":                     (2, "supervised"),
    "k-Means":                  (2, "unsupervised"),
    "PCA":                      (2, "unsupervised"),
    "Autoencoders":             (3, "unsupervised"),
    "Random Forest":            (3, "ensemble"),
    "Gradient Boosting":        (3, "ensemble"),
    "XGBoost":                  (3, "ensemble"),
    "Neural Networks":          (3, "neural"),
    "CNNs":                     (4, "neural"),
    "RNNs":                     (4, "neural"),
    "LSTMs":                    (4, "neural"),
    "Attention Mechanism":      (4, "neural"),
    "Transformers":             (5, "advanced"),
    "BERT / GPT":               (5, "advanced"),
    "Diffusion Models":         (5, "advanced"),
    "Reinforcement Learning":   (5, "advanced"),
    "LLM Fine-tuning":          (6, "advanced"),
    "Meta-Learning":            (6, "advanced"),
}

EDGES = [
    ("Linear Algebra", "Gradient Descent"),
    ("Calculus", "Gradient Descent"),
    ("Calculus", "Backpropagation"),
    ("Probability & Stats", "Loss Functions"),
    ("Probability & Stats", "Logistic Regression"),
    ("Python", "Feature Engineering"),
    ("Loss Functions", "Linear Regression"),
    ("Loss Functions", "Logistic Regression"),
    ("Gradient Descent", "Neural Networks"),
    ("Gradient Descent", "Linear Regression"),
    ("Backpropagation", "Neural Networks"),
    ("Regularization", "Linear Regression"),
    ("Regularization", "Neural Networks"),
    ("Linear Algebra", "PCA"),
    ("Linear Algebra", "SVM"),
    ("Decision Trees", "Random Forest"),
    ("Decision Trees", "Gradient Boosting"),
    ("Gradient Boosting", "XGBoost"),
    ("Neural Networks", "CNNs"),
    ("Neural Networks", "RNNs"),
    ("RNNs", "LSTMs"),
    ("LSTMs", "Attention Mechanism"),
    ("Attention Mechanism", "Transformers"),
    ("Neural Networks", "Autoencoders"),
    ("Transformers", "BERT / GPT"),
    ("Transformers", "Diffusion Models"),
    ("Transformers", "LLM Fine-tuning"),
    ("Neural Networks", "Reinforcement Learning"),
    ("Reinforcement Learning", "Meta-Learning"),
    ("BERT / GPT", "LLM Fine-tuning"),
]

CATEGORY_COLORS = {
    "foundation":   "#1a6985",
    "core":         "#c17d1a",
    "supervised":   "#2d8a4e",
    "unsupervised": "#7b3fa0",
    "ensemble":     "#1a7a6b",
    "neural":       "#1a4da0",
    "advanced":     "#a01a1a",
}
